/**
 * One-time transform script.
 *
 * Pulls the full Google Fonts catalog via the Web Fonts Developer API
 * (requires GOOGLE_FONTS_API_KEY — dev-time only, the running app never
 * calls this API) and reshapes each entry into the Font type, writing a
 * static .ts file to /data/fonts/. Mirrors scripts/transformColors.ts.
 *
 * Google's API gives real facts (family, category, weights) but no
 * qualitative data — mood/style/useCase/note are derived from category
 * with a small heuristic table below, the same "real but templated"
 * approach data/colors/tailwind.ts uses for its auto-generated notes.
 * The 36 fonts in data/fonts/seed.ts are hand-curated with real pairing
 * data and bespoke notes; this file doesn't touch or duplicate those.
 *
 * Run once, whenever the catalog should be refreshed:
 *   npx tsx scripts/transformFonts.ts
 */
import fs from "fs";
import path from "path";
import { Font, FontCategory, FontUseCase } from "../types/font";

// Minimal .env.local loader — avoids adding a dotenv dependency for a
// one-off dev script. next dev loads .env.local itself at runtime; this
// script runs outside Next, so it needs to load it manually.
function loadEnvLocal() {
  const envPath = path.join(__dirname, "../.env.local");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf-8").split("\n")) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2].trim();
    }
  }
}
loadEnvLocal();

type GoogleFont = {
  family: string;
  variants: string[];
  category: string;
};

type GoogleFontsResponse = {
  items: GoogleFont[];
};

const CATEGORY_PROFILE: Record<
  FontCategory,
  { mood: string[]; style: string[]; useCase: FontUseCase[] }
> = {
  "sans-serif": { mood: ["clean", "neutral", "modern"], style: ["minimal", "modern"], useCase: ["body", "heading"] },
  serif: { mood: ["elegant", "classic", "warm"], style: ["vintage", "modern"], useCase: ["heading", "body"] },
  display: { mood: ["bold", "expressive", "energetic"], style: ["bold", "modern"], useCase: ["heading", "accent"] },
  handwriting: { mood: ["playful", "warm", "personal"], style: ["vintage", "pastel"], useCase: ["accent"] },
  monospace: { mood: ["tech", "neutral", "precise"], style: ["minimal", "modern"], useCase: ["code", "accent"] },
  variable: { mood: ["modern", "flexible"], style: ["minimal", "modern"], useCase: ["body", "heading"] },
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function extractWeights(variants: string[]): string[] {
  const weights = new Set<string>();
  for (const v of variants) {
    if (v === "regular") weights.add("400");
    else if (v === "italic") continue;
    else if (/^\d+$/.test(v)) weights.add(v);
    // skip "700italic" etc — Font.variants tracks weight, not style axis
  }
  return Array.from(weights).sort((a, b) => Number(a) - Number(b));
}

function buildNote(family: string, category: FontCategory, weightCount: number): string {
  return `${family} — a ${category} typeface from the Google Fonts catalog, available in ${weightCount} weight${weightCount === 1 ? "" : "s"}.`;
}

function toFont(g: GoogleFont): Font | null {
  const category = g.category as FontCategory;
  const profile = CATEGORY_PROFILE[category];
  if (!profile) return null; // skip anything outside our known categories

  const variants = extractWeights(g.variants);
  if (variants.length === 0) return null;

  return {
    id: `gf-${slugify(g.family)}`,
    family: g.family,
    category,
    variants,
    mood: profile.mood,
    style: profile.style,
    era: "contemporary",
    useCase: profile.useCase,
    googleFontsId: g.family,
    isPro: false,
    pairsWith: [],
    note: buildNote(g.family, category, variants.length),
  };
}

async function main() {
  const apiKey = process.env.GOOGLE_FONTS_API_KEY;
  if (!apiKey) {
    console.error("GOOGLE_FONTS_API_KEY is not set in .env.local");
    process.exit(1);
  }

  const url = `https://www.googleapis.com/webfonts/v1/webfonts?key=${apiKey}&sort=popularity`;
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`Google Fonts API request failed: ${res.status} ${res.statusText}`);
    process.exit(1);
  }

  const data = (await res.json()) as GoogleFontsResponse;
  const fonts = data.items.map(toFont).filter((f): f is Font => f !== null);

  const outDir = path.join(__dirname, "../data/fonts");
  fs.mkdirSync(outDir, { recursive: true });

  const fileContents = `// AUTO-GENERATED by scripts/transformFonts.ts — do not edit by hand.
// Full Google Fonts catalog. See data/fonts/seed.ts for the hand-curated
// set with real pairing data and bespoke editorial notes.
import { Font } from "@/types/font";

export const googleFonts: Font[] = ${JSON.stringify(fonts, null, 2)};
`;

  fs.writeFileSync(path.join(outDir, "google.ts"), fileContents);
  console.log(`Wrote ${fonts.length} Google Fonts to data/fonts/google.ts`);
}

main();
