/**
 * One-time transform script.
 *
 * Pulls Tailwind's built-in colour palette (no API call — it's a local npm
 * package) and Material Design's published colours, reshapes each into the
 * Color type, and writes static .ts files into /data/colors/.
 *
 * Run once after `npm install`:
 *   npm run transform:colors
 *
 * The output files are committed to the repo. The app imports them directly
 * at build/runtime — no network request happens when a user visits the site.
 */
import fs from "fs";
import path from "path";
// Requires `tailwindcss` to be installed (already in package.json deps).
import tailwindColors from "tailwindcss/colors";
import { buildColor } from "../lib/colors/colorUtils";
import { Color, ColorFamily } from "../types/color";

const SKIP_KEYS = new Set(["inherit", "current", "transparent", "black", "white"]);

// Map Tailwind's colour family names onto our ColorFamily union.
const FAMILY_MAP: Record<string, ColorFamily> = {
  slate: "neutral",
  gray: "neutral",
  zinc: "neutral",
  neutral: "neutral",
  stone: "neutral",
  red: "red",
  orange: "orange",
  amber: "orange",
  yellow: "yellow",
  lime: "green",
  green: "green",
  emerald: "green",
  teal: "teal",
  cyan: "teal",
  sky: "blue",
  blue: "blue",
  indigo: "blue",
  violet: "purple",
  purple: "purple",
  fuchsia: "pink",
  pink: "pink",
  rose: "pink",
};

function titleCase(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

// Every Tailwind shade (50–950) maps onto one of these tier words so no
// color ever ships as a bare number like "Red 750" — same light-to-dark
// vocabulary the curated library uses (see scripts/generateCuratedColors.ts),
// so a shade's name alone hints at where it sits on the ramp.
const TIER_BY_SHADE: Record<string, { word: string; note: string }> = {
  "50": { word: "Whisper", note: "so faint it nearly disappears into the page" },
  "100": { word: "Pale", note: "soft enough to sit behind content without competing with it" },
  "200": { word: "Soft", note: "gentle and easy on the eye, good for large surfaces" },
  "300": { word: "Light", note: "clear and approachable, sits comfortably as a secondary tone" },
  "400": { word: "Fair", note: "even-toned and easygoing, a dependable UI colour" },
  "500": { word: "True", note: "the colour in its truest, most balanced form" },
  "600": { word: "Bold", note: "confident and saturated, built to anchor a single focal point" },
  "700": { word: "Rich", note: "deep and full-bodied, reads as premium rather than loud" },
  "800": { word: "Deep", note: "dark and weighty, good for grounding a palette" },
  "900": { word: "Shadow", note: "dark and a little moody, sits closer to black than to its own family" },
  "950": { word: "Midnight", note: "as dark as the family gets, nearly swallowed by black" },
};

function generateNote(subfamily: string, shadeNum: number, tierNote: string): string {
  return `${titleCase(subfamily)} — part of Tailwind's default palette — ${tierNote}.`;
}

function buildTailwindColors(): Color[] {
  const out: Color[] = [];

  for (const [familyKey, shades] of Object.entries(tailwindColors)) {
    if (SKIP_KEYS.has(familyKey) || typeof shades !== "object") continue;
    const family = FAMILY_MAP[familyKey] ?? "neutral";

    for (const [shade, hex] of Object.entries(shades as Record<string, string>)) {
      if (typeof hex !== "string") continue;
      const shadeNum = Number(shade);
      const id = `tw-${familyKey}-${shade}`;
      const tier = TIER_BY_SHADE[shade] ?? { word: "True", note: "a dependable, versatile shade" };

      out.push(
        buildColor({
          id,
          name: `${tier.word} ${titleCase(familyKey)}`,
          hex,
          family,
          mood: shadeNum >= 600 ? ["moody"] : shadeNum <= 200 ? ["calm"] : ["energetic"],
          style: shadeNum <= 200 ? ["pastel"] : shadeNum >= 700 ? ["bold"] : ["modern"],
          collection: "tailwind",
          isPro: shadeNum % 200 === 0, // arbitrary placeholder gating, adjust later
          note: generateNote(familyKey, shadeNum, tier.note),
        })
      );
    }
  }

  return out;
}

function main() {
  const colors = buildTailwindColors();
  const outDir = path.join(__dirname, "../data/colors");
  fs.mkdirSync(outDir, { recursive: true });

  const fileContents = `// AUTO-GENERATED by scripts/transformColors.ts — do not edit by hand.
import { Color } from "@/types/color";

export const tailwindColors: Color[] = ${JSON.stringify(colors, null, 2)};
`;

  fs.writeFileSync(path.join(outDir, "tailwind.ts"), fileContents);
  console.log(`Wrote ${colors.length} Tailwind colours to data/colors/tailwind.ts`);
}

main();