// One-time transform script: pulls real photos from the Unsplash API across
// mood/style search terms matching the 12 ThemeCategory values, and writes
// a static .ts file — the running app never calls Unsplash at runtime.
// Images are hotlinked (Unsplash's recommended approach), never downloaded,
// each carrying the photographer + Unsplash credit their API terms require.
// Run whenever the library should be refreshed: npx tsx scripts/transformMoodboards.ts
import fs from "fs";
import path from "path";
import { MoodboardImage } from "../types/designTokens";

function loadEnvLocal() {
  const envPath = path.join(__dirname, "../.env.local");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf-8").split("\n")) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2].trim();
    }
  }
}
loadEnvLocal();

// One search term + mood tag set per ThemeCategory (types/theme.ts).
const SEARCH_TERMS: Array<{ query: string; mood: string[] }> = [
  { query: "minimalist interior", mood: ["minimal", "calm", "airy", "neutral"] },
  { query: "bold colorful interior design", mood: ["bold", "energetic", "vibrant"] },
  { query: "luxury interior design", mood: ["luxury", "elegant", "sophisticated"] },
  { query: "playful colorful room", mood: ["playful", "fun", "bright"] },
  { query: "earthy natural interior", mood: ["earthy", "natural", "organic", "warm"] },
  { query: "modern tech office", mood: ["tech", "modern", "sleek"] },
  { query: "elegant interior design", mood: ["elegant", "refined", "muted"] },
  { query: "retro vintage interior", mood: ["retro", "vintage", "nostalgic"] },
  { query: "neon aesthetic photography", mood: ["neon", "bold", "nightlife", "digital"] },
  { query: "coastal beach house interior", mood: ["coastal", "airy", "relaxed", "natural-light"] },
  { query: "editorial fashion photography", mood: ["editorial", "sophisticated", "dramatic"] },
  { query: "brutalist architecture", mood: ["brutalist", "stark", "structural"] },
];

const PER_TERM = 9;

type UnsplashPhoto = {
  id: string;
  alt_description: string | null;
  urls: { regular: string };
  links: { html: string };
  user: { name: string; links: { html: string } };
};

type UnsplashSearchResponse = {
  results: UnsplashPhoto[];
};

async function searchUnsplash(query: string, accessKey: string): Promise<UnsplashPhoto[]> {
  const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=${PER_TERM}&orientation=landscape`;
  const res = await fetch(url, { headers: { Authorization: `Client-ID ${accessKey}` } });
  if (!res.ok) {
    throw new Error(`Unsplash search failed for "${query}": ${res.status} ${res.statusText}`);
  }
  const data = (await res.json()) as UnsplashSearchResponse;
  return data.results;
}

function toMoodboardImage(photo: UnsplashPhoto, mood: string[], slugPrefix: string, index: number): MoodboardImage {
  const utm = "utm_source=stylebook&utm_medium=referral";
  return {
    id: `${slugPrefix}-${index}`,
    src: photo.urls.regular,
    alt: photo.alt_description ?? `${slugPrefix} photograph`,
    mood,
    credit: {
      photographerName: photo.user.name,
      photographerUrl: `${photo.user.links.html}?${utm}`,
      unsplashUrl: `${photo.links.html}?${utm}`,
    },
  };
}

async function main() {
  const accessKey = process.env.UNSPLASH_ACCESS_KEY;
  if (!accessKey) {
    console.error("UNSPLASH_ACCESS_KEY is not set in .env.local");
    process.exit(1);
  }

  const allImages: MoodboardImage[] = [];

  for (const { query, mood } of SEARCH_TERMS) {
    const slugPrefix = query
      .split(" ")[0]
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "");
    console.log(`Searching "${query}"...`);
    const photos = await searchUnsplash(query, accessKey);
    photos.forEach((photo, i) => {
      allImages.push(toMoodboardImage(photo, mood, slugPrefix, i));
    });
    // Unsplash's demo rate limit is 50 req/hour — a small pause keeps us
    // well clear of it without meaningfully slowing this one-time script.
    await new Promise((resolve) => setTimeout(resolve, 300));
  }

  const outDir = path.join(__dirname, "../data/moodboards");
  fs.mkdirSync(outDir, { recursive: true });

  const fileContents = `// AUTO-GENERATED by scripts/transformMoodboards.ts — do not edit by hand.
// Real photos from Unsplash, hotlinked (not self-hosted) per Unsplash's
// own recommended usage — see the credit field on each entry. See
// data/moodboards/seed.ts for the hand-curated starter set.
import { MoodboardImage } from "@/types/designTokens";

export const unsplashMoodboardImages: MoodboardImage[] = ${JSON.stringify(allImages, null, 2)};
`;

  fs.writeFileSync(path.join(outDir, "unsplash.ts"), fileContents);
  console.log(`Wrote ${allImages.length} moodboard images to data/moodboards/unsplash.ts`);
}

main();
