/**
 * One-time transform script.
 *
 * Pulls Tailwind's built-in colour palette (no API call — it's a local npm
 * package) and Material Design's published colours, reshapes each into the
 * Color type, and writes static .ts files into /data/colors/.
 *
 * Run once after `npm install`:
 *   npm run transform:colors
 *
 * The output files are committed to the repo. The app imports them directly
 * at build/runtime — no network request happens when a user visits the site.
 */
import fs from "fs";
import path from "path";
// Requires `tailwindcss` to be installed (already in package.json deps).
import tailwindColors from "tailwindcss/colors";
import { buildColor } from "../lib/colors/colorUtils";
import { Color, ColorFamily } from "../types/color";

const SKIP_KEYS = new Set(["inherit", "current", "transparent", "black", "white"]);

// Map Tailwind's colour family names onto our ColorFamily union.
const FAMILY_MAP: Record<string, ColorFamily> = {
  slate: "neutral",
  gray: "neutral",
  zinc: "neutral",
  neutral: "neutral",
  stone: "neutral",
  red: "red",
  orange: "orange",
  amber: "orange",
  yellow: "yellow",
  lime: "green",
  green: "green",
  emerald: "green",
  teal: "teal",
  cyan: "teal",
  sky: "blue",
  blue: "blue",
  indigo: "blue",
  violet: "purple",
  purple: "purple",
  fuchsia: "pink",
  pink: "pink",
  rose: "pink",
};

function titleCase(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function buildTailwindColors(): Color[] {
  const out: Color[] = [];

  for (const [familyKey, shades] of Object.entries(tailwindColors)) {
    if (SKIP_KEYS.has(familyKey) || typeof shades !== "object") continue;
    const family = FAMILY_MAP[familyKey] ?? "neutral";

    for (const [shade, hex] of Object.entries(shades as Record<string, string>)) {
      if (typeof hex !== "string") continue;
      const shadeNum = Number(shade);
      const id = `tw-${familyKey}-${shade}`;

      out.push(
        buildColor({
          id,
          name: `${titleCase(familyKey)} ${shade}`,
          hex,
          family,
          note: "Neutral and airy, useful as a soft foundation for larger surfaces.", //Add the minimum compatibility note for the design
          mood: shadeNum >= 600 ? ["moody"] : shadeNum <= 200 ? ["calm"] : ["energetic"],
          style: shadeNum <= 200 ? ["pastel"] : shadeNum >= 700 ? ["bold"] : ["modern"],
          collection: "tailwind",
          isPro: shadeNum % 200 === 0, // arbitrary placeholder gating, adjust later
        })
      );
    }
  }

  return out;
}

function main() {
  const colors = buildTailwindColors();
  const outDir = path.join(__dirname, "../data/colors");
  fs.mkdirSync(outDir, { recursive: true });

  const fileContents = `// AUTO-GENERATED by scripts/transformColors.ts — do not edit by hand.
import { Color } from "@/types/color";

export const tailwindColors: Color[] = ${JSON.stringify(colors, null, 2)};
`;

  fs.writeFileSync(path.join(outDir, "tailwind.ts"), fileContents);
  console.log(`Wrote ${colors.length} Tailwind colours to data/colors/tailwind.ts`);
}

main();