// AUTO-GENERATED by scripts/transformMoodboards.ts — do not edit by hand.
// Real photos from Unsplash, hotlinked (not self-hosted) per Unsplash's
// own recommended usage — see the credit field on each entry. See
// data/moodboards/seed.ts for the hand-curated starter set.
import { MoodboardImage } from "@/types/designTokens";

export const unsplashMoodboardImages: MoodboardImage[] = [
  {
    "id": "minimalist-0",
    "src": "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white wooden table near brown chair",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Bench Accounting",
      "photographerUrl": "https://unsplash.com/@benchaccounting?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-wooden-table-near-brown-chair-nvzvOPQW0gc?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-1",
    "src": "https://images.unsplash.com/photo-1705321963943-de94bb3f0dd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a living room with a couch and a table",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Pipcke",
      "photographerUrl": "https://unsplash.com/@pipcke?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-with-a-couch-and-a-table-g_5UyVBIX_k?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-2",
    "src": "https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "gray 2 seat sofa near brown wooden coffee table",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Katja Rooke",
      "photographerUrl": "https://unsplash.com/@rooke?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/gray-2-seat-sofa-near-brown-wooden-coffee-table-77JACslA8G0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-3",
    "src": "https://images.unsplash.com/photo-1724582586529-62622e50c0b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A modern living room with a large window",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Prydumano Design",
      "photographerUrl": "https://unsplash.com/@prydumanodesign?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-modern-living-room-with-a-large-window-vIbxvHj9m9g?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-4",
    "src": "https://images.unsplash.com/photo-1617326021886-53d6be1d7154?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white sofa near round table",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Deconovo",
      "photographerUrl": "https://unsplash.com/@deconovo?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-sofa-near-round-table-eNHZC6dEi0Y?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-5",
    "src": "https://images.unsplash.com/photo-1664711942326-2c3351e215e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a room with a couch and a table",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Kam Idris",
      "photographerUrl": "https://unsplash.com/@ka_idris?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-room-with-a-couch-and-a-table-U39FPHKfDu0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-6",
    "src": "https://images.unsplash.com/photo-1713286663271-809d910c0c65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a chair and a table in a room",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Visual Laurence",
      "photographerUrl": "https://unsplash.com/@visuallaurence?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-chair-and-a-table-in-a-room-al0srakHkkY?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-7",
    "src": "https://images.unsplash.com/photo-1625585598750-3535fe40efb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white round table near white wall",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Andrew Neel",
      "photographerUrl": "https://unsplash.com/@andrewtneel?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-round-table-near-white-wall-DLD5LvnFblU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "minimalist-8",
    "src": "https://images.unsplash.com/photo-1617597835919-3fdbf6efe48d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8bWluaW1hbGlzdCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and brown spiral staircase",
    "mood": [
      "minimal",
      "calm",
      "airy",
      "neutral"
    ],
    "credit": {
      "photographerName": "Deconovo",
      "photographerUrl": "https://unsplash.com/@deconovo?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-brown-spiral-staircase-5l6PTBM2smI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-0",
    "src": "https://images.unsplash.com/photo-1618221381711-42ca8ab6e908?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "orange and black sofa with throw pillows",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Spacejoy",
      "photographerUrl": "https://unsplash.com/@spacejoy?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/orange-and-black-sofa-with-throw-pillows-q3Qd86sfaoU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-1",
    "src": "https://images.unsplash.com/photo-1631509716275-59e9d106504a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "green and purple flower in blue ceramic vase on brown wooden table",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Spacejoy",
      "photographerUrl": "https://unsplash.com/@spacejoy?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/green-and-purple-flower-in-blue-ceramic-vase-on-brown-wooden-table-fCfzthk-1mU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-2",
    "src": "https://images.unsplash.com/photo-1631510083755-11ecb5172d81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "green and white throw pillows on green sofa",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Spacejoy",
      "photographerUrl": "https://unsplash.com/@spacejoy?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/green-and-white-throw-pillows-on-green-sofa-ml2RSaDME-k?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-3",
    "src": "https://images.unsplash.com/photo-1659640219304-b5656eee3465?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a living room with a blue couch and a vase with flowers",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Steph Wilson",
      "photographerUrl": "https://unsplash.com/@stephwilll?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-with-a-blue-couch-and-a-vase-with-flowers-ACyOx6nOtdI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-4",
    "src": "https://images.unsplash.com/photo-1783369322310-6790ca2cb2d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Colorful block wall in a vibrant room through brick archway.",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Jerome Cha",
      "photographerUrl": "https://unsplash.com/@jcpny?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/colorful-block-wall-in-a-vibrant-room-through-brick-archway-hxlMMS1O_n8?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-5",
    "src": "https://images.unsplash.com/photo-1759840472798-b7d3fef93643?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Modern staircase illuminated with rainbow colors",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Sabrina Wendl",
      "photographerUrl": "https://unsplash.com/@alightproduction_by_sabrinawendl?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/modern-staircase-illuminated-with-rainbow-colors-JPzaNvXD5bU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-6",
    "src": "https://images.unsplash.com/photo-1774375275542-0750b9418ee3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Four colorful surfaces meeting at a central point.",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Jonas Gerlach",
      "photographerUrl": "https://unsplash.com/@jonasgerlach?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/four-colorful-surfaces-meeting-at-a-central-point-tuekBuIbfPk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-7",
    "src": "https://images.unsplash.com/photo-1774375275392-e84633075f2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Four colorful geometric shapes on a white background",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Jonas Gerlach",
      "photographerUrl": "https://unsplash.com/@jonasgerlach?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/four-colorful-geometric-shapes-on-a-white-background-SRX0QCbi-PI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "bold-8",
    "src": "https://images.unsplash.com/photo-1763311849929-90ec93c144ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8Ym9sZCUyMGNvbG9yZnVsJTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Colorful geometric pattern with triangles and squares.",
    "mood": [
      "bold",
      "energetic",
      "vibrant"
    ],
    "credit": {
      "photographerName": "Jonas Gerlach",
      "photographerUrl": "https://unsplash.com/@jonasgerlach?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/colorful-geometric-pattern-with-triangles-and-squares-iSdCGLPGfLs?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-0",
    "src": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and brown living room set",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Spacejoy",
      "photographerUrl": "https://unsplash.com/@spacejoy?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-brown-living-room-set-9M66C_w_ToM?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-1",
    "src": "https://images.unsplash.com/photo-1606744824163-985d376605aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "black metal framed glass top table",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Jason Wang",
      "photographerUrl": "https://unsplash.com/@coohom?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/black-metal-framed-glass-top-table-NxAwryAbtIw?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-2",
    "src": "https://images.unsplash.com/photo-1503174971373-b1f69850bded?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "two black suede armchairs during daytime",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Alberto Castillo Q.",
      "photographerUrl": "https://unsplash.com/@alcasqui?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/two-black-suede-armchairs-during-daytime-mx4mSkK9zeo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-3",
    "src": "https://images.unsplash.com/photo-1562438668-bcf0ca6578f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "gray bed in bedroom",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "刘 强",
      "photographerUrl": "https://unsplash.com/@iwood?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/gray-bed-in-bedroom-R5v8Xtc0ecg?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-4",
    "src": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white mattress beside sectional sofa",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Roberto Nickson",
      "photographerUrl": "https://unsplash.com/@rpnickson?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-mattress-beside-sectional-sofa-emqnSQwQQDo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-5",
    "src": "https://images.unsplash.com/photo-1738168246881-40f35f8aba0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A living room with a large green couch",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Prydumano Design",
      "photographerUrl": "https://unsplash.com/@prydumanodesign?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-with-a-large-green-couch-VZ2z8ozzy10?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-6",
    "src": "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white ceramic bathtub",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Jared Rice",
      "photographerUrl": "https://unsplash.com/@jareddrice?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-ceramic-bathtub-PibraWHb4h8?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-7",
    "src": "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "brown wooden bed frame with white and red floral bed linen",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Rod Long",
      "photographerUrl": "https://unsplash.com/@rodlong?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/brown-wooden-bed-frame-with-white-and-red-floral-bed-linen-2P_ifaetDm0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "luxury-8",
    "src": "https://images.unsplash.com/photo-1613082294483-fec382d8367e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8bHV4dXJ5JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MHwwfHx8MTc4NDU2OTc4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and black wooden table with chairs",
    "mood": [
      "luxury",
      "elegant",
      "sophisticated"
    ],
    "credit": {
      "photographerName": "Lotus Design N Print",
      "photographerUrl": "https://unsplash.com/@lotusdnp?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-black-wooden-table-with-chairs-xroM8RaMnSI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-0",
    "src": "https://images.unsplash.com/photo-1723359724788-677dca927b8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A child's bedroom with yellow walls and a white rug",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Dream Touch Architects Ltd",
      "photographerUrl": "https://unsplash.com/@interiordesign1?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-childs-bedroom-with-yellow-walls-and-a-white-rug-QUazjRfnhdQ?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-1",
    "src": "https://images.unsplash.com/photo-1708032563898-9ed0c17117b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a computer monitor sitting on top of a white table",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Branden Skeli",
      "photographerUrl": "https://unsplash.com/@branden_skeli?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-computer-monitor-sitting-on-top-of-a-white-table-aKm6lteAIpQ?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-2",
    "src": "https://images.unsplash.com/photo-1600173868911-23137600bed9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and pink floral window curtain",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Atikah Akhtar",
      "photographerUrl": "https://unsplash.com/@atikahakhtar?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-pink-floral-window-curtain-I862k_Zcy9o?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-3",
    "src": "https://images.unsplash.com/photo-1570875628502-54c2f99c8b17?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "blue and white striped bedspread",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Paolo Chiabrando",
      "photographerUrl": "https://unsplash.com/@chiabra?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/blue-and-white-striped-bedspread-jFAKHOcxcAw?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-4",
    "src": "https://images.unsplash.com/photo-1774375275392-e84633075f2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Four colorful geometric shapes on a white background",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Jonas Gerlach",
      "photographerUrl": "https://unsplash.com/@jonasgerlach?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/four-colorful-geometric-shapes-on-a-white-background-SRX0QCbi-PI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-5",
    "src": "https://images.unsplash.com/photo-1758687126595-edcb2bdf03bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Family having a pillow fight on the couch.",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Vitaly Gariev",
      "photographerUrl": "https://unsplash.com/@silverkblack?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/family-having-a-pillow-fight-on-the-couch-Y33Ot4M_33E?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-6",
    "src": "https://images.unsplash.com/photo-1783961859503-2f6cd85f6e87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Colorful living room with geometric wall design and plants",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Fujiphilm",
      "photographerUrl": "https://unsplash.com/@fujiphilm?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/colorful-living-room-with-geometric-wall-design-and-plants-IGTzLb0QMvA?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-7",
    "src": "https://images.unsplash.com/photo-1681912818658-57e5438fcd3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a room with a lot of art on the wall",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "BoliviaInteligente",
      "photographerUrl": "https://unsplash.com/@boliviainteligente?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-room-with-a-lot-of-art-on-the-wall-gzf1SuC_rP4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "playful-8",
    "src": "https://images.unsplash.com/photo-1678182450248-525b93183b10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8cGxheWZ1bCUyMGNvbG9yZnVsJTIwcm9vbXxlbnwwfDB8fHwxNzg0NTY5NzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a child's room with orange walls and blue walls",
    "mood": [
      "playful",
      "fun",
      "bright"
    ],
    "credit": {
      "photographerName": "Ali Mkumbwa",
      "photographerUrl": "https://unsplash.com/@mkumbwajr?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-childs-room-with-orange-walls-and-blue-walls-atKxpkI1-x0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-0",
    "src": "https://images.unsplash.com/photo-1509069800611-748cec24c744?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "selective focus photography of green-leafed plants",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "Nong",
      "photographerUrl": "https://unsplash.com/@californong?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/selective-focus-photography-of-green-leafed-plants-FbKJz4kCdQI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-1",
    "src": "https://images.unsplash.com/photo-1776721976768-7a392044d0f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Woven straw baskets hang on a green wall.",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "Jonathan Borba",
      "photographerUrl": "https://unsplash.com/@jonathanborba?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/woven-straw-baskets-hang-on-a-green-wall-A99Dnq4k-P0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-2",
    "src": "https://images.unsplash.com/photo-1763978485095-1cd13f4d3cb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Luxurious bathroom with stone sinks and rustic decor.",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "POOJAN THANEKAR",
      "photographerUrl": "https://unsplash.com/@poojanclicks?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/luxurious-bathroom-with-stone-sinks-and-rustic-decor-58qHGTnnUIo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-3",
    "src": "https://images.unsplash.com/photo-1656740840031-41cb3bc73c01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a greenhouse with plants",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "neil macc",
      "photographerUrl": "https://unsplash.com/@neilmaccs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-greenhouse-with-plants-KGIhqNaqq2s?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-4",
    "src": "https://images.unsplash.com/photo-1656740839066-db82019b292b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a group of potted plants",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "neil macc",
      "photographerUrl": "https://unsplash.com/@neilmaccs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-group-of-potted-plants-je5fQD0fbCM?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-5",
    "src": "https://images.unsplash.com/photo-1656740839909-b1a6a72767ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a greenhouse with many plants",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "neil macc",
      "photographerUrl": "https://unsplash.com/@neilmaccs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-greenhouse-with-many-plants-MAiiZyijBlU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-6",
    "src": "https://images.unsplash.com/photo-1656740835412-f0514c91c3e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a greenhouse with plants and trees",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "neil macc",
      "photographerUrl": "https://unsplash.com/@neilmaccs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-greenhouse-with-plants-and-trees-4E9e_28pyYM?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-7",
    "src": "https://images.unsplash.com/photo-1656740840036-7744c5bce4fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a greenhouse with many plants",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "neil macc",
      "photographerUrl": "https://unsplash.com/@neilmaccs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-greenhouse-with-many-plants-t9-cFs4nGgQ?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "earthy-8",
    "src": "https://images.unsplash.com/photo-1656740840026-1258041b73f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8ZWFydGh5JTIwbmF0dXJhbCUyMGludGVyaW9yfGVufDB8MHx8fDE3ODQ1Njk3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a greenhouse with plants",
    "mood": [
      "earthy",
      "natural",
      "organic",
      "warm"
    ],
    "credit": {
      "photographerName": "neil macc",
      "photographerUrl": "https://unsplash.com/@neilmaccs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-greenhouse-with-plants-PL21hhFrZhg?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-0",
    "src": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "photo of dining table and chairs inside room",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Nastuh Abootalebi",
      "photographerUrl": "https://unsplash.com/@sunday_digital?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/photo-of-dining-table-and-chairs-inside-room-eHD8Y1Znfpk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-1",
    "src": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "hallway between glass-panel doors",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Nastuh Abootalebi",
      "photographerUrl": "https://unsplash.com/@sunday_digital?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/hallway-between-glass-panel-doors-yWwob8kwOCk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-2",
    "src": "https://images.unsplash.com/photo-1559136555-9303baea8ebd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "man standing beside another sitting man using computer",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Proxyclick Visitor Management System",
      "photographerUrl": "https://unsplash.com/@proxyclick?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/man-standing-beside-another-sitting-man-using-computer-l90zRbWvCoE?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-3",
    "src": "https://images.unsplash.com/photo-1556761175-4b46a572b786?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "man in blue dress shirt sitting on rolling chair inside room with monitors",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Austin Distel",
      "photographerUrl": "https://unsplash.com/@austindistel?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/man-in-blue-dress-shirt-sitting-on-rolling-chair-inside-room-with-monitors-wawEfYdpkag?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-4",
    "src": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "black floor lamp on living room sofa",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Toa Heftiba",
      "photographerUrl": "https://unsplash.com/@heftiba?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/black-floor-lamp-on-living-room-sofa-FV3GConVSss?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-5",
    "src": "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "people sitting on chair in front of computer",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Israel Andrade",
      "photographerUrl": "https://unsplash.com/@israelandrxde?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/people-sitting-on-chair-in-front-of-computer-YI_9SivVt_s?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-6",
    "src": "https://images.unsplash.com/photo-1531973576160-7125cd663d86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "three people collaborating in open office",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "LYCS Architecture",
      "photographerUrl": "https://unsplash.com/@lycs?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/three-people-collaborating-in-open-office-U2BI3GMnSSE?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-7",
    "src": "https://images.unsplash.com/photo-1718220216044-006f43e3a9b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "an office with a lot of desks and chairs",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Bernd 📷 Dittrich",
      "photographerUrl": "https://unsplash.com/@hdbernd?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/an-office-with-a-lot-of-desks-and-chairs-pYlBAu3de0w?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "modern-8",
    "src": "https://images.unsplash.com/photo-1558959356-2f36c7322d3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8bW9kZXJuJTIwdGVjaCUyMG9mZmljZXxlbnwwfDB8fHwxNzg0NTY5NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "man walking on stairs",
    "mood": [
      "tech",
      "modern",
      "sleek"
    ],
    "credit": {
      "photographerName": "Proxyclick Visitor Management System",
      "photographerUrl": "https://unsplash.com/@proxyclick?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/man-walking-on-stairs-3h7j04-6y3Q?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-0",
    "src": "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white wooden coffee table near white sofa",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "Lotus Design N Print",
      "photographerUrl": "https://unsplash.com/@lotusdnp?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-wooden-coffee-table-near-white-sofa-WgkA3CSFrjc?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-1",
    "src": "https://images.unsplash.com/photo-1558442074-3c19857bc1dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "rectangular white coffee table near brown leather sofa",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "iD INTERIORS",
      "photographerUrl": "https://unsplash.com/@idinteriors?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/rectangular-white-coffee-table-near-brown-leather-sofa-VWt1BBQwwtU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-2",
    "src": "https://images.unsplash.com/photo-1648881806148-e5c51179c826?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a living room filled with furniture and a chandelier",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "Ali Moradi",
      "photographerUrl": "https://unsplash.com/@3dartistmoradi?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-chandelier-nhzhEZvhZ1M?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-3",
    "src": "https://images.unsplash.com/photo-1653972233499-eaad56990299?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a living room filled with furniture and a chandelier",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "dada_design",
      "photographerUrl": "https://unsplash.com/@dada_design?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-chandelier-8aQnBInxp1s?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-4",
    "src": "https://images.unsplash.com/photo-1742541656775-5fc717774c02?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Modern living room with neutral colors and elegant design.",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "Home Makers Interior",
      "photographerUrl": "https://unsplash.com/@homemakersinterior?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/modern-living-room-with-neutral-colors-and-elegant-design-3b5uYZIIoc0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-5",
    "src": "https://images.unsplash.com/photo-1734937743443-a50fff0c0b40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A living room filled with furniture and a flat screen TV",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "Home Makers Interior",
      "photographerUrl": "https://unsplash.com/@homemakersinterior?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-flat-screen-tv-9mSYc-zKdWA?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-6",
    "src": "https://images.unsplash.com/photo-1745301558339-44eb3217d5da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A luxurious, modern living room with exquisite design.",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "Spl Interiors",
      "photographerUrl": "https://unsplash.com/@spl_interiors?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-luxurious-modern-living-room-with-exquisite-design-oaITdLL7bD4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-7",
    "src": "https://images.unsplash.com/photo-1618221312573-404f9a52798d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and gold pendant lamp",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "Spacejoy",
      "photographerUrl": "https://unsplash.com/@spacejoy?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-gold-pendant-lamp-2d1k_A-nrY8?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "elegant-8",
    "src": "https://images.unsplash.com/photo-1653972233739-667468bbd5a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8ZWxlZ2FudCUyMGludGVyaW9yJTIwZGVzaWdufGVufDB8MHx8fDE3ODQ1Njk3ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a living room filled with furniture and a chandelier",
    "mood": [
      "elegant",
      "refined",
      "muted"
    ],
    "credit": {
      "photographerName": "dada_design",
      "photographerUrl": "https://unsplash.com/@dada_design?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-chandelier-K3kRm4025G8?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-0",
    "src": "https://images.unsplash.com/photo-1577176434922-803273eba97a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "brown wooden chairs, table, and cabinet",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Fujiphilm",
      "photographerUrl": "https://unsplash.com/@fujiphilm?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/brown-wooden-chairs-table-and-cabinet-oujKSaZlMFY?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-1",
    "src": "https://images.unsplash.com/photo-1563373011-d9b2e9af4167?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "no people sitting at the table in room",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Amel Majanovic",
      "photographerUrl": "https://unsplash.com/@just_amelo?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/no-people-sitting-at-the-table-in-room-0s-D2GUrC-A?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-2",
    "src": "https://images.unsplash.com/photo-1579236546973-39f510ef2a37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "red leather bench inside room",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Dayanara Peenee",
      "photographerUrl": "https://unsplash.com/@dayanaranacion?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/red-leather-bench-inside-room-HuIJUp6gTDI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-3",
    "src": "https://images.unsplash.com/photo-1504105547124-fc1aee34470d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "vointage brown radio on black wooden table",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Csongor Schmutc",
      "photographerUrl": "https://unsplash.com/@schmutccsongor?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/vointage-brown-radio-on-black-wooden-table-WximLTzm94E?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-4",
    "src": "https://images.unsplash.com/photo-1679926591722-79bff79c561a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a kitchen with a table and a refrigerator",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Jakob Owens",
      "photographerUrl": "https://unsplash.com/@jakobowens1?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-kitchen-with-a-table-and-a-refrigerator-A1nc0u93y9w?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-5",
    "src": "https://images.unsplash.com/photo-1554857042-666bcbcaa512?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "vintage car on table",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Ori Song",
      "photographerUrl": "https://unsplash.com/@ori_foto?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/vintage-car-on-table-d6xmGBg5_-4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-6",
    "src": "https://images.unsplash.com/photo-1748507494897-265aaa4e46cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A quirky restaurant interior with a yellow vw truck.",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "mohammed ahmed",
      "photographerUrl": "https://unsplash.com/@hama_assets?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-quirky-restaurant-interior-with-a-yellow-vw-truck-bd9gG72uUK4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-7",
    "src": "https://images.unsplash.com/photo-1622550875302-5a49e664c32d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and brown concrete building",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "Annie Spratt",
      "photographerUrl": "https://unsplash.com/@anniespratt?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-brown-concrete-building-_WkAiZyEqKY?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "retro-8",
    "src": "https://images.unsplash.com/photo-1748507494892-9e5bc3e830d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8cmV0cm8lMjB2aW50YWdlJTIwaW50ZXJpb3J8ZW58MHwwfHx8MTc4NDU2OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A retro-style diner with a volkswagen truck.",
    "mood": [
      "retro",
      "vintage",
      "nostalgic"
    ],
    "credit": {
      "photographerName": "mohammed ahmed",
      "photographerUrl": "https://unsplash.com/@hama_assets?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-retro-style-diner-with-a-volkswagen-truck-82hOVXrUGZc?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-0",
    "src": "https://images.unsplash.com/photo-1519608487953-e999c86e7455?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "people walking on walkway during nighttime",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "kevin laminto",
      "photographerUrl": "https://unsplash.com/@kxvn_lx?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/people-walking-on-walkway-during-nighttime-7PqRZK6rbaE?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-1",
    "src": "https://images.unsplash.com/photo-1503058474900-cb76710f9cd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "midnight city road",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Dan Gold",
      "photographerUrl": "https://unsplash.com/@danielcgold?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/midnight-city-road-CCKcwh7s9A4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-2",
    "src": "https://images.unsplash.com/photo-1599060052009-24d6d0b0161c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "people walking on street during night time",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Hiep Duong",
      "photographerUrl": "https://unsplash.com/@hiepdaiduong93?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/people-walking-on-street-during-night-time-Z0aBm6359Oo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-3",
    "src": "https://images.unsplash.com/photo-1529573813483-53bd9ede667e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "sweet escape neon sign on wooden pier",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Let's go Together",
      "photographerUrl": "https://unsplash.com/@lets_go_together?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/sweet-escape-neon-sign-on-wooden-pier-orYix9zFUZo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-4",
    "src": "https://images.unsplash.com/photo-1512064275189-98e71acc1eae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "With All Your heart neon signage",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Brittney Burnett",
      "photographerUrl": "https://unsplash.com/@brittneyburnett?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/with-all-your-heart-neon-signage-qFS2hU6DFhk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-5",
    "src": "https://images.unsplash.com/photo-1713630019375-f483a9729a8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a bunch of cars parked in front of a store",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Jahanzeb Ahsan",
      "photographerUrl": "https://unsplash.com/@jahan_photobox?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-bunch-of-cars-parked-in-front-of-a-store-7gSgXv-MqGI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-6",
    "src": "https://images.unsplash.com/photo-1544194215-541c2d3561a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "life is beautiful LED signage",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Katarzyna Grabowska",
      "photographerUrl": "https://unsplash.com/@kalljet?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/life-is-beautiful-led-signage-rMYGCAI_-zU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-7",
    "src": "https://images.unsplash.com/photo-1549147133-8450b6fe7ef3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "good vibes only neon signage",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "Maryna Yazbeck",
      "photographerUrl": "https://unsplash.com/@yazbeckistan?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/good-vibes-only-neon-signage-f7sVtG_cMdk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "neon-8",
    "src": "https://images.unsplash.com/photo-1508179522353-11ba468c4a1c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8bmVvbiUyMGFlc3RoZXRpYyUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "man looking at glass storefront windowpane during night",
    "mood": [
      "neon",
      "bold",
      "nightlife",
      "digital"
    ],
    "credit": {
      "photographerName": "chester wade",
      "photographerUrl": "https://unsplash.com/@chesterwade?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/man-looking-at-glass-storefront-windowpane-during-night-msnyz9L6gs4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-0",
    "src": "https://images.unsplash.com/photo-1770414173168-f6c666501225?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A bright, coastal-themed bedroom with a large bed.",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "amelia elite",
      "photographerUrl": "https://unsplash.com/@ameliaelite?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-bright-coastal-themed-bedroom-with-a-large-bed-d6jN8t0GUF4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-1",
    "src": "https://images.unsplash.com/photo-1767362218280-34ebf49b0621?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Curtains with heart decorations frame ocean view",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Thamy N.",
      "photographerUrl": "https://unsplash.com/@thamyn?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/curtains-with-heart-decorations-frame-ocean-view-hskb_rJhHuw?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-2",
    "src": "https://images.unsplash.com/photo-1771992457574-c71812f066be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Glass vase filled with pearlescent shells",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Iris Yan",
      "photographerUrl": "https://unsplash.com/@iriiiis?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/glass-vase-filled-with-pearlescent-shells-UF3utVeMhWk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-3",
    "src": "https://images.unsplash.com/photo-1760067538612-c0ecd3bc3d3a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Modern living room with large couch and indoor plants",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Alef Morais",
      "photographerUrl": "https://unsplash.com/@aleff_jpg?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/modern-living-room-with-large-couch-and-indoor-plants-DY7wJD6Ly2s?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-4",
    "src": "https://images.unsplash.com/photo-1760067537620-6aaab015fba5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Living room with sofa, tv, and indoor plants.",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Alef Morais",
      "photographerUrl": "https://unsplash.com/@aleff_jpg?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/living-room-with-sofa-tv-and-indoor-plants-U8oMMM6FRsE?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-5",
    "src": "https://images.unsplash.com/photo-1773609688944-b506930a047c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Three decorative boats with anchors and flags",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Alexander von Schulz",
      "photographerUrl": "https://unsplash.com/@jastorfproductions?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/three-decorative-boats-with-anchors-and-flags-T9_R5nSjcq0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-6",
    "src": "https://images.unsplash.com/photo-1779332183022-4691d4e16113?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Fishhouse sign with decorative fish and colorful string lights.",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Sunira Moses",
      "photographerUrl": "https://unsplash.com/@sunira?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/fishhouse-sign-with-decorative-fish-and-colorful-string-lights-RLqUpUK0bTA?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-7",
    "src": "https://images.unsplash.com/photo-1760067537723-bb12d2674e15?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Bedroom with two beds and decorative paddles.",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Alef Morais",
      "photographerUrl": "https://unsplash.com/@aleff_jpg?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/bedroom-with-two-beds-and-decorative-paddles-afUquqyGVGo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "coastal-8",
    "src": "https://images.unsplash.com/photo-1760067538068-03d10481bacb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8Y29hc3RhbCUyMGJlYWNoJTIwaG91c2UlMjBpbnRlcmlvcnxlbnwwfDB8fHwxNzg0NTY5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "Bedroom with bed, television, and open doorway to bathroom.",
    "mood": [
      "coastal",
      "airy",
      "relaxed",
      "natural-light"
    ],
    "credit": {
      "photographerName": "Alef Morais",
      "photographerUrl": "https://unsplash.com/@aleff_jpg?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/bedroom-with-bed-television-and-open-doorway-to-bathroom-9Ap0MhvjmZw?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-0",
    "src": "https://images.unsplash.com/photo-1662532577856-e8ee8b138a8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a person in a red dress",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Marjan Taghipour",
      "photographerUrl": "https://unsplash.com/@marjantaghipour?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-person-in-a-red-dress-1tjMpBTvFAA?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-1",
    "src": "https://images.unsplash.com/photo-1612731486606-2614b4d74921?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "woman in black blazer smiling",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Dominik kielbasa",
      "photographerUrl": "https://unsplash.com/@dbasa?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/woman-in-black-blazer-smiling-ssnCzNayHC4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-2",
    "src": "https://images.unsplash.com/photo-1700150662401-9b96a5fedfbb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a woman is sitting on a chair with her hand on her hip",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Joss Broward",
      "photographerUrl": "https://unsplash.com/@jossbroward?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-woman-is-sitting-on-a-chair-with-her-hand-on-her-hip-PFF6kI0HeOs?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-3",
    "src": "https://images.unsplash.com/photo-1693129499971-ae047f40ca70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a woman standing in front of a colorful curtain",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Mariela Ferbo",
      "photographerUrl": "https://unsplash.com/@marielaferbo?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-woman-standing-in-front-of-a-colorful-curtain-zyo97FvVNko?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-4",
    "src": "https://images.unsplash.com/photo-1700150649421-f0577c19fa69?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a woman sitting on top of a metal chair",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Joss Broward",
      "photographerUrl": "https://unsplash.com/@jossbroward?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-woman-sitting-on-top-of-a-metal-chair-qQ0g2swKLhU?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-5",
    "src": "https://images.unsplash.com/photo-1700150615736-e90e9037b8e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a young man sitting on the ground wearing a turtle neck sweater",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Joss Broward",
      "photographerUrl": "https://unsplash.com/@jossbroward?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-young-man-sitting-on-the-ground-wearing-a-turtle-neck-sweater-MfDi5tFzj50?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-6",
    "src": "https://images.unsplash.com/photo-1700150607117-ebff107cbe2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a man in a green sweater and black pants",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Joss Broward",
      "photographerUrl": "https://unsplash.com/@jossbroward?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-man-in-a-green-sweater-and-black-pants-cTi0omFcZo0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-7",
    "src": "https://images.unsplash.com/photo-1728279900274-706566e3ca08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A woman in a white dress sitting on a hill",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Alvensia Angela",
      "photographerUrl": "https://unsplash.com/@alvensiangela?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-woman-in-a-white-dress-sitting-on-a-hill-5z0DCivrraM?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "editorial-8",
    "src": "https://images.unsplash.com/photo-1728280342639-4a14d782966d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8ZWRpdG9yaWFsJTIwZmFzaGlvbiUyMHBob3RvZ3JhcGh5fGVufDB8MHx8fDE3ODQ1Njk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "A young girl standing in the water with her hands on her head",
    "mood": [
      "editorial",
      "sophisticated",
      "dramatic"
    ],
    "credit": {
      "photographerName": "Alvensia Angela",
      "photographerUrl": "https://unsplash.com/@alvensiangela?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-young-girl-standing-in-the-water-with-her-hands-on-her-head-yaJK-4T0HbI?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-0",
    "src": "https://images.unsplash.com/photo-1488972685288-c3fd157d7c7a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8MXx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "low angle photography of gray building at daytime",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Anders Jildén",
      "photographerUrl": "https://unsplash.com/@andersjilden?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/low-angle-photography-of-gray-building-at-daytime-Sc5RKXLBjGg?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-1",
    "src": "https://images.unsplash.com/photo-1546414701-81cc6963c67f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Mnx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "landscape photography of gray concrete building",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Simone Hutsch",
      "photographerUrl": "https://unsplash.com/@heysupersimi?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/landscape-photography-of-gray-concrete-building-XK0faa4_mCQ?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-2",
    "src": "https://images.unsplash.com/photo-1504625709867-b4e45e3bb9dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8M3x8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "architectural photo of building",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Christophe Laurenceau",
      "photographerUrl": "https://unsplash.com/@justcallmechristophe?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/architectural-photo-of-building-MPWbGMrZ6eo?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-3",
    "src": "https://images.unsplash.com/photo-1446771326090-d910bfaf00f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NHx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "3D artwork illustration",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Carl Nenzen Loven",
      "photographerUrl": "https://unsplash.com/@archduk3?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/3d-artwork-illustration-busqfOj6i80?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-4",
    "src": "https://images.unsplash.com/photo-1531591022136-eb8b0da1e6d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8NXx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "white and black abstract painting",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Tobias Keller",
      "photographerUrl": "https://unsplash.com/@tokeller?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/white-and-black-abstract-painting-2ecH5Lw3zSk?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-5",
    "src": "https://images.unsplash.com/photo-1625390711106-3728815ebcd9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8Nnx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "gray concrete building during daytime",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Ricardo Gomez Angel",
      "photographerUrl": "https://unsplash.com/@rgaleriacom?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/gray-concrete-building-during-daytime-9AjwOAIdsII?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-6",
    "src": "https://images.unsplash.com/photo-1506749841726-3df2e72b9564?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8N3x8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "spiral gray steel tunnel",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Arturo Castaneyra",
      "photographerUrl": "https://unsplash.com/@arturokst?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/spiral-gray-steel-tunnel-o-dkYSvidB4?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-7",
    "src": "https://images.unsplash.com/photo-1483366774565-c783b9f70e2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OHx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "worm's-eye view photography of concrete building",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "Kimon Maritz",
      "photographerUrl": "https://unsplash.com/@kimonmaritz?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/worms-eye-view-photography-of-concrete-building-mQiZnKwGXW0?utm_source=stylebook&utm_medium=referral"
    }
  },
  {
    "id": "brutalist-8",
    "src": "https://images.unsplash.com/photo-1634573826817-27d9e8da08df?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDAzMDQzfDB8MXxzZWFyY2h8OXx8YnJ1dGFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDB8MHx8fDE3ODQ1Njk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "alt": "a reflection of a building in a body of water",
    "mood": [
      "brutalist",
      "stark",
      "structural"
    ],
    "credit": {
      "photographerName": "William Priess",
      "photographerUrl": "https://unsplash.com/@william_priess?utm_source=stylebook&utm_medium=referral",
      "unsplashUrl": "https://unsplash.com/photos/a-reflection-of-a-building-in-a-body-of-water-1jyHQxBAE7A?utm_source=stylebook&utm_medium=referral"
    }
  }
];
